//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public string examinateID { get; set; }
        public string patientID { get; set; }
        public string employeeID { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<int> breathing { get; set; }
        public string symptom { get; set; }
        public Nullable<int> veins { get; set; }
        public Nullable<int> bloodPressure { get; set; }
        public string preliminaryDiagnosis { get; set; }
        public string finalDiagnosis { get; set; }
        public string treatmentDirection { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
