//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Medicine
    {
        public string prescriptionID { get; set; }
        public string medicineName { get; set; }
        public int quanlity { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
