//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ListMedicine_Precesciption
    {
        public string prescriptionID { get; set; }
        public string examinateID { get; set; }
        public string patientID { get; set; }
        public string employeeID { get; set; }
        public string medicineID { get; set; }
        public string medicineName { get; set; }
        public int quanlity { get; set; }
        public Nullable<int> medicinePrice { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public byte status { get; set; }
    }
}
