//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Staff
    {
        public string doctorID { get; set; }
        public string doctorFirstname { get; set; }
        public string doctorLastName { get; set; }
        public string sex { get; set; }
        public System.DateTime birthDay { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string cardID { get; set; }
        public string departmentName { get; set; }
        public string departmentID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
